const urls =[
    "https://www.adl.com.tr/kadin-kazak/",
    "https://www.beymen.com/tr/kadin-giyim-triko-kazak-10048",
    "https://www.bsl.com.tr/tr/triko-kazak/",
    "https://www.defacto.com.tr/kadin-kazak",
    "https://www.koton.com/kadin-kazak-suveter/",
    "https://www.lcw.com/kadin-kazak-t-202",
    "https://www.lovemybody.com.tr/kazak/",
    "https://shop.mango.com/tr/tr/c/kadin/kazaklar-ve-h%C4%B1rkalar_f9a8c868",
    "https://markapia.com/kadin-kazak-hirka",
    "https://www.network.com.tr/kadin-kazak-cesitleri-1325",
    "https://www.nocturne.com.tr/triko",
    "https://www.oxxo.com.tr/tr/giyim/trikolar/",
    "https://www.patirti.com/triko/",
    "https://www.sementa.com/collections/kadin-kazak",
    "https://www.mudo.com.tr/kadin-kazak/",
    "https://gustoeshop.com/triko-kazak",
    "https://www.ekolonline.com/triko-kazak",
    "https://www.ipekyol.com.tr/giyim/triko-modelleri",
    "https://www.twist.com.tr/kadin-triko-kazak",
    "https://www.colins.com.tr/c/kadin-kazak-199",
    "https://www.pullandbear.com/tr/kadin/giyim/triko-n6618",
    "https://www.bershka.com/tr/kadin/giyim/triko-n3844.html",
    "https://joinus.com.tr/collections/kadin-kazak",
    "https://clothing.beautyomelette.com/kadin-triko",
    "https://www.sherin.com.tr/kadin-kazak-modelleri",
    "https://www.ozsaricam.com/kazak"
]

export default urls