name: kanald
on:
   workflow_dispatch:
    inputs:
      site:
        description: 'site'
        required: true
        type: string
jobs:
  kadin_job:
    uses: ./.github/workflows/reusable.yml
    with:
      site: ${{inputs.site}}
    secrets: inherit
