name: ngmedia
on:
  schedule:
    - cron:  '0 0 * * 4'
env:
  MONGODB_URL: ${{secrets.MONGODB_URL}}
  GH_TOKEN: ${{secrets.GH_TOKEN}}
jobs:
  kadin_job:
    uses: ./.github/workflows/reusable.yml
    with:
      gitFolder: tvseries
      site: 'ngmedia'
    secrets: inherit
