name: Sponsor Product Scraping

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 2'  # Brooksbrothers on Tuesday
    - cron: '0 0 * * 3'  # Othersite1 on Wednesday
    - cron: '0 0 * * 4'  # Othersite2 on Thursday

env:
  MONGODB_URL: ${{secrets.MONGODB_URL}}
  GH_TOKEN: ${{secrets.GH_TOKEN}}

jobs:
  dizitv_job:
    strategy:
      matrix:
        include:
          - site: desa
            schedule: '0 0 * * 2'  # Tuesday
          - site: divarese
            schedule: '0 0 * * 3'  # Wednesday
          - site: elleshoes
            schedule: '0 0 * * 4'  # Thursday

    uses: ./.github/workflows/reusableProdPuppeteer.yml
    with:
      site: ${{ matrix.site }}
      # gitFolder: sponsor-product
    secrets: inherit