name: sponsorProdMat
on:
  workflow_dispatch:
    inputs:
      sites:
        description: 'Comma-separated list of sites'
        required: true
        type: string
      gitFolder:
        description: 'gitFolder'
        required: true
        type: string

env:
  MONGODB_URL: ${{secrets.MONGODB_URL}}
  GH_TOKEN: ${{secrets.GH_TOKEN}}

jobs:
  generate_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Split sites into matrix
        id: set-matrix
        run: |
          sites=(${{ inputs.sites//,/ }})
          echo "matrix=$(jq -n --argjson sites "$(printf '%s\n' "${sites[@]}" | jq -R . | jq -s .)" '{"include": [{"site": $sites[]}]}')" >> $GITHUB_OUTPUT

  dizitv_job:
    needs: generate_matrix
    uses: ./.github/workflows/reusableProdPuppeteer.yml
    strategy:
      matrix: ${{ fromJson(needs.generate_matrix.outputs.matrix) }}
    with:
      site: ${{ matrix.site }}
      gitFolder: ${{ inputs.gitFolder }}
    secrets: inherit
