name: sponsorProdManualAggregPuppeteerMulti
on:
  workflow_dispatch:
    inputs:
      sites:
        description: 'Comma-separated list of sites'
        required: true
        type: string

env:
  MONGODB_URL: ${{ secrets.MONGODB_URL }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  create_jobs:
    runs-on: ubuntu-latest
    outputs:
      site_list: ${{ steps.prepare.outputs.site_list }}
    steps:
      - name: Prepare site list
        id: prepare
        run: echo "::set-output name=site_list::$(echo '${{ inputs.sites }}' | tr ',' '\n')"

  run_puppeteer:
    needs: create_jobs
    strategy:
      matrix:
        site: ${{ fromJson(needs.create_jobs.outputs.site_list) }}
    uses: ./.github/workflows/reusableProdPuppeteer.yml
    with:
      site: ${{ matrix.site }}
    secrets: inherit
