name: sponsorProdMatrix
   workflow_dispatch:
    inputs:
      sites:   # Comma-separated list of sites
        description: 'Comma-separated list of target sites'
        required: true
        type: string
      gitFolder:
        description: 'Git folder'
        required: true
        type: string
env:
  MONGODB_URL: ${{ secrets.MONGODB_URL }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  process_sites:
    runs-on: ubuntu-latest
    outputs:
      sites: ${{ steps.split_sites.outputs.sites_json }}
    steps:
      - name: Split sites into JSON array
        id: split_sites
        run: |
          sites_json=$(echo "${{ inputs.sites }}" | jq -R 'split(",")')
          echo "sites_json=$sites_json" >> $GITHUB_OUTPUT
        env:
          SITES: ${{ inputs.sites }}

  # Job to run reusable workflow for each site
  site_jobs:
    needs: process_sites
    runs-on: ubuntu-latest
    strategy:
      matrix:
        site: ${{ fromJson(needs.process_sites.outputs.sites) }}
    uses: ./.github/workflows/reusableProdPuppeteer.yml
    with:
      site: ${{ matrix.site }}
      gitFolder: ${{ inputs.gitFolder }}
    secrets: inherit
