name: sponsorProdManualMAtrixAggregPuppeteer
on:
   workflow_dispatch:
    inputs:
      sites:
        description: 'Comma-separated list of sites'
        required: true
        type: string
      gitFolder:
        description: 'gitFolder'
        required: true
        type: string
env:
  MONGODB_URL: ${{secrets.MONGODB_URL}}
  GH_TOKEN: ${{secrets.GH_TOKEN}}
jobs:
  dizitv_job:
    strategy:
      matrix:
        site: ${{ fromCSV(inputs.sites) }}
    uses: ./.github/workflows/reusableProdPuppeteer.yml
    with:
      site: ${{ matrix.site }}
      gitFolder: ${{inputs.gitFolder}}
    secrets: inherit