name: sponsorKKKK
on:
   workflow_dispatch:
env:
  MONGODB_URL: ${{secrets.MONGODB_URL}}
  GH_TOKEN: ${{secrets.GH_TOKEN}}
jobs:
  prepare_matrix:
    runs-on: ubuntu-latest
    outputs:
      sites: ${{ steps.set-sites.outputs.sites }}
    steps:
      - id: set-sites
        run: |
          SITES_ARRAY='["koton", "defacto"]'
          echo "sites=$SITES_ARRAY" >> $GITHUB_OUTPUT

  dizitv_job:
    needs: prepare_matrix
    strategy:
      matrix:
        site: ${{ fromJSON(needs.prepare_matrix.outputs.sites) }}
    uses: ./.github/workflows/reusableProdPuppeteer.yml
    with:
      site: ${{ matrix.site }}
    secrets: inherit