name: sponsorProdMatzx
on:
  workflow_dispatch:
    inputs:
      sites:
        description: 'Comma-separated list of sites'
        required: true
        type: string

env:
  MONGODB_URL: ${{ secrets.MONGODB_URL }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  generate_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Create matrix from input
        id: set-matrix
        run: |
          sites="${{ inputs.sites }}"
          site_array=(${sites//,/ })   # Splitting by comma
          json=$(jq -n --argjson sites "$(printf '%s\n' "${site_array[@]}" | jq -R . | jq -s .)" '{"include": [{"site": $sites[]}]}')
          echo "matrix=${json}" >> $GITHUB_OUTPUT

  dizitv_job:
    needs: generate_matrix
    uses: ./.github/workflows/reusableProdPuppeteer.yml
    strategy:
      matrix: ${{ fromJson(needs.generate_matrix.outputs.matrix).include }}
    with:
      site: ${{ matrix.site }}
    secrets: inherit
