name: sponsorProdManuaMatrix
on:
   workflow_dispatch:
    inputs:
      sites:   # Renamed from 'site' to 'sites'
        description: 'Comma-separated list of target sites'
        required: true
        type: string
      gitFolder:
        description: 'Git folder'
        required: true
        type: string
env:
  MONGODB_URL: ${{secrets.MONGODB_URL}}
  GH_TOKEN: ${{secrets.GH_TOKEN}}

jobs:
  process_sites:
    runs-on: ubuntu-latest
    steps:
      - name: Split sites into array
        id: split_sites
        run: |
          echo "sites=$(echo '${{ inputs.sites }}' | tr ',' '\n')" >> $GITHUB_ENV

  # Dynamically create jobs for each site
  site_jobs:
    needs: process_sites
    runs-on: ubuntu-latest
    strategy:
      matrix:
        site: ${{ fromJson(env.sites) }}
    uses: ./.github/workflows/reusableProdPuppeteer.yml
    with:
      site: ${{ matrix.site }}
      gitFolder: ${{ inputs.gitFolder }}
    secrets: inherit
