name: sponsorProdManualAggreg
on:
   workflow_dispatch:
    inputs:
      site:
        description: 'site'
        required: true
        type: string
      gitFolder:
        description: 'gitFolder'
        required: true
        type: string
env:
  MONGODB_URL: ${{secrets.MONGODB_URL}}
  GH_TOKEN: ${{secrets.GH_TOKEN}}
jobs:
  dizitv_job:
    uses: ./.github/workflows/reusableProd.yml
    with:
      site: ${{inputs.site}}
      gitFolder: ${{inputs.gitFolder}}
    secrets: inherit
