name: sponsorProdssssss
on:
  workflow_dispatch:
    inputs:
      sites:
        description: 'Comma-separated list of sites'
        required: true
        type: string
      gitFolder:
        description: 'gitFolder'
        required: true
        type: string

env:
  MONGODB_URL: ${{ secrets.MONGODB_URL }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  dizitv_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        site: [${{ fromJson(inputs.sites) }}]
    
    steps:
      - name: Run Puppeteer for each site
        uses: ./.github/workflows/reusableProdPuppeteer.yml
        with:
          site: ${{ matrix.site }}
          gitFolder: ${{ inputs.gitFolder }}
        secrets: inherit